version: "3.6"
services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: lakeshore_dev
      POSTGRES_PASSWORD: spraylakeshore123
      POSTGRES_DB: spraylakeshore
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
